name: Free up disk space
description: Free up disk space see https://github.com/actions/runner-images/issues/10511
runs:
  using: "composite"
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        xcrun simctl delete all
        sudo rm -rf ~/Library/Developer/CoreSimulator/Caches/*
        sudo rm -rf /Applications/Xcode_14.3.1.app
