name: Build (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build-ios-macos:
    name: Build iOS/macOS artifacts (RN 0.71)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free space
        uses: ./.github/workflows/macos_freespace

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.26.3'

      - name: Setup Ninja
        run: brew install ninja

      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: NPM Install (Playground)
        run: npm install
        working-directory: ./Apps/Playground

      - name: Select React Native Version 0.71
        run: npm run select --reactNative 0.71
        working-directory: ./Apps/Playground

      - name: NPM Install (Binary Package)
        run: npm install
        working-directory: ./Package

      - name: Build (Gulp) - iOS and macOS
        run: npx gulp build --reactNative 0.71 --releaseVersion 0.0.0-pr
        working-directory: ./Package
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      - name: Upload Assembled iOS macOS Folder
        uses: actions/upload-artifact@v4
        with:
          name: 'Assembled-iOSmacOS0.71'
          path: Package/Assembled-iOSmacOS

      - name: Upload Assembled iOS macOS BaseKit Folder
        uses: actions/upload-artifact@v4
        with:
          name: 'Assembled-BaseKit-iOSmacOS0.71'
          path: Package/Assembled-BaseKit-iOSmacOS