name: Release

on:
  release:
    types: [published, prereleased]
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  sanity:
    name: Release trigger check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print release context
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "release_id=${{ github.event.release.id }}"
            echo "tag_name=${{ github.event.release.tag_name }}"
          fi
